### ISSUE TITLE
Sand Box Mobile Verification Issue

### ISSUE THREAD

**Issue by zubyf09** [bitreserve/bitreserve-sdk-android#47]
I am trying to make a Sandbox account but it is not sending me confrimation code on my mobile Device?is teir any bug in your sandBox Enviornment.Please check this issue as soon as possible.I tried it form US and Pakistan.

**Comment by ruipenso** [comment]
The verification code is `0000000`. You can read more about it [here](https://developer.bitreserve.org/en/sandbox).

**Comment by zubyf09** [comment]
thanks
