### ISSUE TITLE
Sand Box Testing Issue? But works fine with live account.

### ISSUE THREAD

**Issue by zubyf09** [bitreserve/bitreserve-sdk-android#50]
I created an app Using  folllowing linke:
https://sandbox.bitreserve.org/dashboard/

Did this code:
public void authanticateBitresever()
{
		try {
			bitreserveClient = new BitreserveClient();
			SecureRandom secureRandom = new SecureRandom();
			state = new BigInteger(130, secureRandom).toString(32);
					ArrayList<String> scopes = new ArrayList<String>() {{
						add("cards:read");
						add("user:read");
					}};
					bitreserveClient.beginAuthorization(this, C.BITRESERVE_CLIENT_ID, scopes, state);

		} catch (BitreserveSdkNotInitializedException e) {
			Log.d(MainActivity.class.toString(), e.getMessage());
		}

	}

In my app i use Client ID and Scret id which is created in sand box environment.
When I tried to authenticate user it takes me to https://bitreserve.org  for login.Logically it should takes me to the sandbox.bitreserve url

And i am getting this message Sorry,Thtat page does'nt exist.
https://bitreserve.org/404

What i am doing wrong? any idea?

I tried it on live account it works fine.

**Comment by SandroMachado** [comment]
In the `build.gradle` of your application in the dependencies section are you importing the sandbox build flavour?  

You need to put in your dependencies  

```gradle
	compile project (path: ':Bitreserve-android-sdk', configuration: 'sandboxRelease')
```

Can your confirm if this is the case?

**Comment by zubyf09** [comment]
Thanks man It's works for me.
Actually i included the Bitreserve Library in a Manual Way so that's why getting this issue.
Really Thanks Sandro <3
