### ISSUE TITLE
Transaction Issue 

### ISSUE THREAD

**Issue by zubyf09** [bitreserve/bitreserve-sdk-android#52]
﹕ {"error":"invalid_scope"}
i am getting this message.

here is my procedure.
First i load cards 

public void loadCards()
{
String bearerToken = sharedPreferences.getString(C.SP_BIT_RESERVE_AUTH_TOKEN,"");
try {
BitreserveClient bitreserveClient = new BitreserveClient(bearerToken);
			bitreserveClient.getUser().then(new RepromiseFunction<User, List<Card>>() {
				@Override
				public Promise<List<Card>> call(User user) {
					// Do something with the user.
					return user.getCardsByCurrency(curency.curencyName);
				}
			}).then(new PromiseAction<List<Card>>() {
				@Override
				public void call(List<Card> cards) {

					card = cards.get(0);
					Toast.makeText(TransactionActivity.this,""+card.getBalance(),Toast.LENGTH_LONG).show();
					// Do something with the list of cards.
				}
			}).fail(new PromiseAction<Exception>() {
				@Override
				public void call(Exception e) {
					// Do something with the error.
				}
			});

			} catch (BitreserveSdkNotInitializedException e) {
				Log.d(MainActivity.class.toString(), e.getMessage());
			}

		}

and Doing Transaciton using this method.

public void doTransaction(BitUser user)
		{

TransactionDenominationRequest transactionDenominationRequest = new TransactionDenominationRequest(user.amount, user.curencyName);
				TransactionRequest transactionRequest = new TransactionRequest(transactionDenominationRequest, user.sendEmail);

card.createTransaction(transactionRequest).then(new PromiseAction<Transaction>() {
					@Override
					public void call(Transaction transaction) {
						// Commit the transaction.
						transaction.commit();

						Toast.makeText(TransactionActivity.this,""+transaction.getMessage(),Toast.LENGTH_LONG).show();;
					}
				});

		}

**Comment by SandroMachado** [comment]
Can you please confirm that you are requesting for the `transactions:write` scope? [More information about the scopes we support] (https://developer.bitreserve.org/api/v0/#permissions)

You need to call the `beginAuthorization`method with a list of scopes similar to this 
```java
ArrayList<String> scopes = new ArrayList<String>() {{
    add("cards:read");
    add("user:read");
    add("transactions:write");
}};

bitreserveClient.beginAuthorization(MainActivity.this, CLIENT_ID, scopes, state);
```

Can your confirm if this is the case?

**Comment by zubyf09** [comment]
No i did not add this..Once Again Thanks.
