### ISSUE TITLE
Is there any method or process which provide transaction success?

### ISSUE THREAD

**Issue by zubyf09** [bitreserve/bitreserve-sdk-android#53]
The code in sample of document 
Transaction.commit()
Then I tried to get transaction status using this
transaction.getstatus() in same call method it return pending status.i just want to know in which method on complete status shows or I have to wait in call method ?

**Comment by SandroMachado** [comment]
To check a transaction status you need to call `transaction.getStatus();` that returns the current transaction status (possible values are: `pending`, `waiting`, `cancelled` or `completed`). 

If you want to check if a transaction status changed, just get the user transactions list (call `user.getUserTransactions()` that returns a `Paginator` with the updated list of transactions) and search for the transaction you want to check (using the transaction id, to get the id call `transaction.getId()`).

**Comment by zubyf09** [comment]
ok
